// THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO ARGO AI, LLC ("ARGO"),
// AND MAY NOT BE COPIED, REPRODUCED, MODIFIED, OR DISTRIBUTED WITHOUT
// ARGO'S PERMISSION.
// Copyright (c) $YEAR$ Argo AI, LLC.

#pragma once

#include <ClassHelper/ClassHelpers.hh>

namespace $NAMESPACE_DOUBLE_COLON$
{

class $COMPONENT_NAME$
{
public:
  $COMPONENT_NAME$();
  ~$COMPONENT_NAME$() = default;
  COPY_CONSTRUCT($COMPONENT_NAME$) = delete;
  COPY_ASSIGN($COMPONENT_NAME$) = delete;
  MOVE_CONSTRUCT($COMPONENT_NAME$) = delete;
  MOVE_ASSIGN($COMPONENT_NAME$) = delete;

private:

};

}  // namespace $NAMESPACE_DOUBLE_COLON$