// THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO ARGO AI, LLC ("ARGO"),
// AND MAY NOT BE COPIED, REPRODUCED, MODIFIED, OR DISTRIBUTED WITHOUT
// ARGO'S PERMISSION.
// Copyright (c) $YEAR$ Argo AI, LLC.

#include "$COMPONENT_NAME$.hh"

namespace $NAMESPACE_DOUBLE_COLON$
{

$COMPONENT_NAME$::$COMPONENT_NAME$()
{

}

}  // namespace $NAMESPACE_DOUBLE_COLON$
