// THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO ARGO AI, LLC ("ARGO"),
// AND MAY NOT BE COPIED, REPRODUCED, MODIFIED, OR DISTRIBUTED WITHOUT
// ARGO'S PERMISSION.
// Copyright (c) 2018 Argo AI, LLC.

#include "$WIDGET_NAME$.hh"

$NAMESPACE_START$

$WIDGET_NAME$::$WIDGET_NAME$()
{
  ui_ = std::make_unique<Ui::$WIDGET_NAME$UI>();
  ui_->setupUi(this);
}

$NAMESPACE_END$
