// THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO ARGO AI, LLC ("ARGO"),
// AND MAY NOT BE COPIED, REPRODUCED, MODIFIED, OR DISTRIBUTED WITHOUT
// ARGO'S PERMISSION.
// Copyright (c) $YEAR$ Argo AI, LLC.

#include "$WIDGET_NAME$.hh"
#include <$FOLDER_NAME$/widgets/ui_$WIDGET_NAME$.h>

namespace $NAMESPACE_DOUBLE_COLON$
{

$WIDGET_NAME$::$WIDGET_NAME$()
{
  ui_ = std::make_unique<Ui::$WIDGET_NAME$UI>();
  ui_->setupUi(this);
}

$WIDGET_NAME$::~$WIDGET_NAME$() = default;

}  // namespace $NAMESPACE_DOUBLE_COLON$
