// THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO ARGO AI, LLC ("ARGO"),
// AND MAY NOT BE COPIED, REPRODUCED, MODIFIED, OR DISTRIBUTED WITHOUT
// ARGO'S PERMISSION.
// Copyright (c) $YEAR$ Argo AI, LLC.

#include "$CONFIG_NAME$.hh"

namespace $NAMESPACE_DOUBLE_COLON$
{

IMPL_CONFIG_TYPE($CONFIG_NAME$)

}  // namespace $NAMESPACE_DOUBLE_COLON$
