// THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO ARGO AI, LLC ("ARGO"),
// AND MAY NOT BE COPIED, REPRODUCED, MODIFIED, OR DISTRIBUTED WITHOUT
// ARGO'S PERMISSION.
// Copyright (c) $YEAR$ Argo AI, LLC.

#include "$CONFIG_NAME$.hh"

$NAMESPACE_START$

IMPL_CONFIG_TYPE($CONFIG_NAME$)

$NAMESPACE_END$
