// THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO ARGO AI, LLC ("ARGO"),
// AND MAY NOT BE COPIED, REPRODUCED, MODIFIED, OR DISTRIBUTED WITHOUT
// ARGO'S PERMISSION.
// Copyright (c) $YEAR$ Argo AI, LLC.

#pragma once

#include <$FOLDER_NAME$/plugins/$CONFIG_NAME$Impl.hh>

#include <Config/ConfigBuilder.hh>

namespace $NAMESPACE_DOUBLE_COLON$
{

class $CONFIG_NAME$ : public $CONFIG_NAME$Impl
{
  DECL_CONFIG_TYPE($CONFIG_NAME$)
};

}  // namespace $NAMESPACE_DOUBLE_COLON$
