// THIS PROGRAM IS CONFIDENTIAL AND PROPRIETARY TO ARGO AI, LLC ("ARGO"),
// AND MAY NOT BE COPIED, REPRODUCED, MODIFIED, OR DISTRIBUTED WITHOUT
// ARGO'S PERMISSION.
// Copyright (c) $YEAR$ Argo AI, LLC.


#include <catch/catch.hpp>

namespace $NAMESPACE_DOUBLE_COLON$
{

TEST_CASE("Test case name")
{
}

}  // namespace $NAMESPACE_DOUBLE_COLON$